"""fix

Revision ID: f7b7dcc2eba5
Revises: c127f1909d0d
Create Date: 2024-09-02 16:26:36.936434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b7dcc2eba5'
down_revision: Union[str, None] = 'c127f1909d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('material_categoty_id_fkey', 'material', type_='foreignkey')
    op.create_foreign_key(None, 'material', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('material', 'categoty_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('categoty_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.create_foreign_key('material_categoty_id_fkey', 'material', 'category', ['categoty_id'], ['id'], ondelete='CASCADE')
    op.drop_column('material', 'category_id')
    # ### end Alembic commands ###
